### NumPy Indexing and Selection 

#### Neste tópico discutiremos como selecionar elementos ou grupos de elementos de um array

In [55]:
import numpy as np

In [56]:
arr = np.arange(0,11)

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Indexando e Selecionando
A primeira e mais fácil forma de obter algum elemento de um array é como já conhecemos em Python, usando o index:

In [58]:
arr[8]

8

In [59]:
arr[1:5]

array([1, 2, 3, 4])

In [60]:
 # lembre-se desta forma o index é inclusivo com o '0' e exclusivo com o '5', que representa a sexta posição, partido do 0
arr[0:5]

array([0, 1, 2, 3, 4])

In [61]:
# Quero tudo até a posição 6
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [62]:
# Quero tudo depois da quinta posição
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

### Broadcasting

#### Numpy arrays são muito parecidos com lists em Python, mas se diferem pela habilidade de "broadcast":

In [63]:
# Instaurando um valor para as posições indexadas do array:
arr[0:5] = 100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [64]:
# Separando um array em pedaços:
arr = np.arange(0,11)

slice_of_arr = arr[0:6]

# Show
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [65]:
# Transformando todos os valores de um array em "99":
slice_of_arr[:] = 99

# Show:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [66]:
# Agora, notaremos que as mudanças não aconteceram somente no "slice_of_array", mas sim também no "arr":
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [67]:
# Os dados não são copiados, mas sim são somente parte dos dados originais. Isso é feito para evitar problemas de memória.
# Para conseguir uma cópia, é preciso ser específico:
arr_copy = arr.copy()

# Show
arr_copy


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Indexando matrizes (2D arrays)

In [68]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

# Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [69]:
# Indexando a linha
arr_2d[0]

array([ 5, 10, 15])

In [70]:
# Indexar com duplos colchetes funciona assim:
# Coletando o elemento "25":
arr_2d[1][1]

25

In [71]:
# O que o professor Portilla indica é usar outra notação, utilizando vírgula:
# Coletando o elemento "25":
arr_2d[1,1]

25

In [72]:
# Assim como num array normal, é possível pegar pedaços de uma matriz:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [73]:
# Coletando tudo até a linha 2 e tudo depois da coluna 1
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [74]:
# Coletando tudo a partir da linha 1 até o final:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [75]:
# Tudo a partir da linha 1 e só os membros da últimas coluna:
arr_2d[1:, 2:]

array([[30],
       [45]])

In [76]:
# Não tem porque se preocupar muito já que essas indexações não são tão utilizadas.
arr =np.arange(0,11)

# Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Fancy Indexing

#### Segundo essa parte especial do Notebook, essa forma de indexar permite selecionar linhas e colunas inteiras fora de sequência.

In [77]:
# Criando a Matrix
arr2d = np.zeros((10,10))

In [78]:
# Tamanho do array
arr_lenght = arr2d.shape[1]

In [79]:
# Set up array

for i in range(arr_lenght):
    arr2d[i] = i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [80]:
# Fancy indexing permite isso:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [81]:
# Permite em qualquer ordem
arr2d[[6,2,8,4]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

### Mais sobre indexação

#### Utilizando colchetes com operadores lógicos para selecionar alguns dados

In [82]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
# Tornando o arr num array de booleanos seguinte a comparação abaixo:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [84]:
# Podemos salvar esse array novo: 
bool_arr = arr > 4

In [85]:
# Agora podemos utilizar bool_ar como uma indexação dentro dos colchetes de um array:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [86]:
# Eu posso passar no próprio index do array a condição:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

Basicamente é, estamos criando uma condição lógica dentro do index do array e a partir do retorno em verdadeiros e falsos
o array é retornado com as posições verdadeiros, como podemos ver nas linhas 44,45,46 e 47

In [87]:
# Agora o professor mostra como retornar algumas posições mais "difíceis" de um array mais complexo,
# Queremos os números: 13, 14, 23, 24 :
arr_2d = np.arange(50).reshape(5,10)

# Show
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [88]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])