## NumPy

NumPy or Numpy is a Linear Algebra Library for Python. The reason it is so important for Data Science with Python is that almost all off the libraries in the PyData ecosystem rely on NumPy as one of the main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Using NumPy

In [3]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [4]:
my_list = [1,2,3]

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [34]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods
There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [15]:
# A lot easier way to creat arrays:
np.arange(0,10)
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
# This another argument of the function: 'Step', where you can choose the number of jumps that you array will have
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [17]:
# Creating an array of 0's:
np.zeros(3)

array([0., 0., 0.])

In [18]:
# Creating another array of 0's, this time a Matrix:
np.zeros((3,3)) # 3 lines and 3 collumns

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# Same thing, but with one:
np.ones(4)

array([1., 1., 1., 1.])

In [36]:
# 3x3 Matrix of ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [37]:
# An Array of 10 numbers where this 10 numberes are between 0 and 5
# The third argument from arange its from the steps, and in linspace it is from the total of numbers
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

## eye

Creates an identity matrix

In [38]:
# Creating an identy matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [27]:
np.random.rand(5)

array([0.19034993, 0.41885633, 0.84535574, 0.56281477, 0.14088182])

In [39]:
np.random.rand(5,5)

array([[0.64774145, 0.71993362, 0.01764755, 0.9324867 , 0.91189231],
       [0.05189302, 0.86873624, 0.73910567, 0.64819478, 0.93521862],
       [0.49941154, 0.26253146, 0.40618848, 0.79816493, 0.62293693],
       [0.82124085, 0.73318565, 0.33640726, 0.28413587, 0.13959441],
       [0.54728719, 0.78794296, 0.41852382, 0.062831  , 0.54957372]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [30]:
np.random.randn(2)

array([ 0.14696206, -0.31135079])

In [40]:
np.random.randn(4,4)

array([[ 1.79122092, -0.36172604, -1.10110926,  0.65881171],
       [-1.50686147,  0.66380477, -1.36935208, -0.20930346],
       [-0.47759068, -0.48362381,  0.59524521,  0.22451446],
       [-1.3159365 ,  0.30818067, -0.41131069,  0.49613169]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [32]:
np.random.randint(1,100)

16

In [33]:
np.random.randint(1,100,10)

array([64, 63, 57, 95,  9, 13, 26, 82,  2, 31])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [41]:
arr = np.arange(25)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
ranarr = np.random.randint(0,50,10)

In [49]:
ranarr

array([10, 30, 29, 21, 19, 42,  5, 15, 31, 36])

## Reshape
Returns an array containing the same data with a new shape.

In [48]:
# Here we transform an 25 array of integers in a 5x5 matrix of intergers
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [50]:
ranarr.max()

42

In [51]:
ranarr.min()

5

In [52]:
ranarr.argmax()

5

In [53]:
ranarr.argmin()

6

## Shape

Shape is an attribute that arrays have (not a method):

In [55]:
# Vector
arr.shape

(25,)

In [56]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [58]:
arr.reshape(1,25).shape

(1, 25)

In [59]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [60]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [61]:
arr.dtype

dtype('int32')

## Extra

In [63]:
# You can import numpy methods, like this:
from numpy.random import randint

In [65]:
# And them, you can use this methods whithout calling the numpy:
randint(1,10,3)

array([9, 5, 7])